# Usar uma imagem oficial do Node.js como base
FROM node:16

# Definir o diretório de trabalho no contêiner
WORKDIR /usr/src/app

# Copiar o package.json e o package-lock.json (se houver)
COPY package*.json ./

# Instalar as dependências do projeto
RUN npm install

# Copiar o restante dos arquivos do projeto para o contêiner
COPY . .

# Expor a porta em que o app vai rodar
EXPOSE 3000

# Definir o comando que será executado quando o contêiner for iniciado
CMD ["npm", "run", "dev"]
